name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # 30분마다 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # 전체 커밋 내역이 필요

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Teachers-Teachmon/StuMon-FE.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "🔄 Sync fork with upstream"

      - name: Push changes to fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
